# Netlify configuration file for Next.js projects.
# This file tells Netlify how to build and deploy your site.
# For more information, see: https://docs.netlify.com/build-settings-overview/

[build]
  # Command to build the project.
  command = "npm run build"

  # The directory that contains the deploy-ready assets.
  # For Next.js, this is the .next directory.
  publish = ".next"

# The Netlify build plugin for Next.js is automatically installed
# when a Next.js project is detected. This plugin handles server-side
# rendering, API routes, and other Next.js features on Netlify.
